# <MODULE_NAME>.<ENTITY_ID>
googlemaps.googlemap.*:
  type: config_object
  label: Google Map
  mapping:
    name:
      type: string
      label: Machine name
    label:
      type: label
      label: Label
    key:
      type: string
      label: API key
    libraries:
      type: sequence
      label: The names of API libraries
      sequence:
        type: string
        label: The name of API library
    callback:
      type: string
      label: Initialization callback
