rng_contact.rng_contact_type.*:
  type: config_entity
  label: 'Contact type'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    courier_email_field:
      type: text
      label: 'ID of email field to use when sending mailings via Courier.'
