<?php

/**
 * @file
 * Google Maps.
 */

use Drupal\Core\Url;

/**
 * Implements hook_library_info_build().
 */
function googlemaps_library_info_build() {
  $libraries = [];

  /** @var \Drupal\googlemaps\Entity\GoogleMap $entity */
  foreach (\Drupal::entityTypeManager()->getStorage('googlemap')->loadMultiple() as $entity) {
    $query = [];

    foreach (['libraries', 'key', 'callback'] as $option) {
      if (!empty($entity->{$option})) {
        $query[$option] = implode(',', (array) $entity->{$option});
      }
    }

    $libraries[$entity->name] = [
      'js' => [
        Url::fromUri('//maps.googleapis.com/maps/api/js', ['query' => $query])->toString() => [],
      ],
    ];
  }

  return $libraries;
}

/**
 * Functional placeholder for library definition.
 *
 * @param string $name
 *   The name of Google Maps instance.
 *
 * @return string
 *   The name of defined library.
 */
function googlemaps_library($name) {
  return "googlemaps/$name";
}
